junior key
https://ai.google.dev/gemini-api/docs/get-started/androidAIzaSyCK1EBghN5IYy2hypK7Qlzwq2CuLR4vA6wbuild.gradle.ktscom.google.ai.client.generativeai.GenerativeModel// In Android Studio, add the following dependency to your build.gradle.kts file:
// implementation("com.google.ai.client.generativeai:generativeai:0.7.0")
//
// See the Getting Started guide for more information:
// https://ai.google.dev/gemini-api/docs/get-started/android

// Add the following code to your Kotlin source code
import com.google.ai.client.generativeai.GenerativeModel

val model = GenerativeModel(
  "gemini-1.5-flash",
  // Retrieve API key as an environmental variable defined in a Build Configuration
  // see https://github.com/google/secrets-gradle-plugin for further instructions
  BuildConfig.geminiApiKey,
  generationConfig = generationConfig {
    temperature = 1f
    topK = 64
    topP = 0.95f
    maxOutputTokens = 8192
    responseMimeType = "text/plain"
  },
  // safetySettings = Adjust safety settings
  // See https://ai.google.dev/gemini-api/docs/safety-settings
)

val response = model.generateContent(
  content() {
    text("junior ")
    text("Moore ")
  }
)

// Get the first text part of the first candidate
println(response.text)
// Alternatively
println(response.candidates.first().content.parts.first().asTextOrNull())
